/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as VendorsSlugRouteImport } from './routes/vendors.$slug'
import { Route as StoneIdRouteImport } from './routes/stone.$id'

const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsSlugRoute = VendorsSlugRouteImport.update({
  id: '/vendors/$slug',
  path: '/vendors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoneIdRoute = StoneIdRouteImport.update({
  id: '/stone/$id',
  path: '/stone/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/marketplace': typeof MarketplaceRoute
  '/stone/$id': typeof StoneIdRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/marketplace': typeof MarketplaceRoute
  '/stone/$id': typeof StoneIdRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/vendors': typeof VendorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/marketplace': typeof MarketplaceRoute
  '/stone/$id': typeof StoneIdRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/vendors/': typeof VendorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/marketplace'
    | '/stone/$id'
    | '/vendors/$slug'
    | '/vendors/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/marketplace'
    | '/stone/$id'
    | '/vendors/$slug'
    | '/vendors'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/marketplace'
    | '/stone/$id'
    | '/vendors/$slug'
    | '/vendors/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  MarketplaceRoute: typeof MarketplaceRoute
  StoneIdRoute: typeof StoneIdRoute
  VendorsSlugRoute: typeof VendorsSlugRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/$slug': {
      id: '/vendors/$slug'
      path: '/vendors/$slug'
      fullPath: '/vendors/$slug'
      preLoaderRoute: typeof VendorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stone/$id': {
      id: '/stone/$id'
      path: '/stone/$id'
      fullPath: '/stone/$id'
      preLoaderRoute: typeof StoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  MarketplaceRoute: MarketplaceRoute,
  StoneIdRoute: StoneIdRoute,
  VendorsSlugRoute: VendorsSlugRoute,
  VendorsIndexRoute: VendorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
