/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VendorsSlugRouteImport } from './routes/vendors.$slug'
import { Route as StoneIdRouteImport } from './routes/stone.$id'
import { Route as SignUpJewellerRouteImport } from './routes/sign-up.jeweller'
import { Route as SignUpDealerRouteImport } from './routes/sign-up.dealer'
import { Route as EmbedKeyRouteImport } from './routes/embed.$key'
import { Route as DashboardImportRouteImport } from './routes/dashboard.import'
import { Route as DashboardEnquiriesRouteImport } from './routes/dashboard.enquiries'
import { Route as DashboardStonesIndexRouteImport } from './routes/dashboard.stones.index'
import { Route as DashboardJewellerIndexRouteImport } from './routes/dashboard.jeweller.index'
import { Route as DashboardStonesNewRouteImport } from './routes/dashboard.stones.new'
import { Route as DashboardStonesIdRouteImport } from './routes/dashboard.stones.$id'
import { Route as DashboardJewellerMarkupRouteImport } from './routes/dashboard.jeweller.markup'
import { Route as DashboardJewellerFeedsRouteImport } from './routes/dashboard.jeweller.feeds'
import { Route as DashboardJewellerEnquiriesRouteImport } from './routes/dashboard.jeweller.enquiries'
import { Route as DashboardJewellerApiRouteImport } from './routes/dashboard.jeweller.api'
import { Route as ApiPublicFeedRouteImport } from './routes/api/public/feed'
import { Route as ApiPublicChaosDotjsRouteImport } from './routes/api/public/chaos[.]js'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VendorsSlugRoute = VendorsSlugRouteImport.update({
  id: '/vendors/$slug',
  path: '/vendors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoneIdRoute = StoneIdRouteImport.update({
  id: '/stone/$id',
  path: '/stone/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpJewellerRoute = SignUpJewellerRouteImport.update({
  id: '/sign-up/jeweller',
  path: '/sign-up/jeweller',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpDealerRoute = SignUpDealerRouteImport.update({
  id: '/sign-up/dealer',
  path: '/sign-up/dealer',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedKeyRoute = EmbedKeyRouteImport.update({
  id: '/embed/$key',
  path: '/embed/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnquiriesRoute = DashboardEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStonesIndexRoute = DashboardStonesIndexRouteImport.update({
  id: '/stones/',
  path: '/stones/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJewellerIndexRoute = DashboardJewellerIndexRouteImport.update({
  id: '/jeweller/',
  path: '/jeweller/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStonesNewRoute = DashboardStonesNewRouteImport.update({
  id: '/stones/new',
  path: '/stones/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStonesIdRoute = DashboardStonesIdRouteImport.update({
  id: '/stones/$id',
  path: '/stones/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJewellerMarkupRoute = DashboardJewellerMarkupRouteImport.update({
  id: '/jeweller/markup',
  path: '/jeweller/markup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJewellerFeedsRoute = DashboardJewellerFeedsRouteImport.update({
  id: '/jeweller/feeds',
  path: '/jeweller/feeds',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJewellerEnquiriesRoute =
  DashboardJewellerEnquiriesRouteImport.update({
    id: '/jeweller/enquiries',
    path: '/jeweller/enquiries',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardJewellerApiRoute = DashboardJewellerApiRouteImport.update({
  id: '/jeweller/api',
  path: '/jeweller/api',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicFeedRoute = ApiPublicFeedRouteImport.update({
  id: '/api/public/feed',
  path: '/api/public/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChaosDotjsRoute = ApiPublicChaosDotjsRouteImport.update({
  id: '/api/public/chaos.js',
  path: '/api/public/chaos.js',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/embed/$key': typeof EmbedKeyRoute
  '/sign-up/dealer': typeof SignUpDealerRoute
  '/sign-up/jeweller': typeof SignUpJewellerRoute
  '/stone/$id': typeof StoneIdRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/api/public/chaos.js': typeof ApiPublicChaosDotjsRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
  '/dashboard/jeweller/api': typeof DashboardJewellerApiRoute
  '/dashboard/jeweller/enquiries': typeof DashboardJewellerEnquiriesRoute
  '/dashboard/jeweller/feeds': typeof DashboardJewellerFeedsRoute
  '/dashboard/jeweller/markup': typeof DashboardJewellerMarkupRoute
  '/dashboard/stones/$id': typeof DashboardStonesIdRoute
  '/dashboard/stones/new': typeof DashboardStonesNewRoute
  '/dashboard/jeweller/': typeof DashboardJewellerIndexRoute
  '/dashboard/stones/': typeof DashboardStonesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/embed/$key': typeof EmbedKeyRoute
  '/sign-up/dealer': typeof SignUpDealerRoute
  '/sign-up/jeweller': typeof SignUpJewellerRoute
  '/stone/$id': typeof StoneIdRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/api/public/chaos.js': typeof ApiPublicChaosDotjsRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
  '/dashboard/jeweller/api': typeof DashboardJewellerApiRoute
  '/dashboard/jeweller/enquiries': typeof DashboardJewellerEnquiriesRoute
  '/dashboard/jeweller/feeds': typeof DashboardJewellerFeedsRoute
  '/dashboard/jeweller/markup': typeof DashboardJewellerMarkupRoute
  '/dashboard/stones/$id': typeof DashboardStonesIdRoute
  '/dashboard/stones/new': typeof DashboardStonesNewRoute
  '/dashboard/jeweller': typeof DashboardJewellerIndexRoute
  '/dashboard/stones': typeof DashboardStonesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/embed/$key': typeof EmbedKeyRoute
  '/sign-up/dealer': typeof SignUpDealerRoute
  '/sign-up/jeweller': typeof SignUpJewellerRoute
  '/stone/$id': typeof StoneIdRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/api/public/chaos.js': typeof ApiPublicChaosDotjsRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
  '/dashboard/jeweller/api': typeof DashboardJewellerApiRoute
  '/dashboard/jeweller/enquiries': typeof DashboardJewellerEnquiriesRoute
  '/dashboard/jeweller/feeds': typeof DashboardJewellerFeedsRoute
  '/dashboard/jeweller/markup': typeof DashboardJewellerMarkupRoute
  '/dashboard/stones/$id': typeof DashboardStonesIdRoute
  '/dashboard/stones/new': typeof DashboardStonesNewRoute
  '/dashboard/jeweller/': typeof DashboardJewellerIndexRoute
  '/dashboard/stones/': typeof DashboardStonesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/marketplace'
    | '/pending-approval'
    | '/sitemap.xml'
    | '/dashboard/enquiries'
    | '/dashboard/import'
    | '/embed/$key'
    | '/sign-up/dealer'
    | '/sign-up/jeweller'
    | '/stone/$id'
    | '/vendors/$slug'
    | '/dashboard/'
    | '/vendors/'
    | '/api/public/chaos.js'
    | '/api/public/feed'
    | '/dashboard/jeweller/api'
    | '/dashboard/jeweller/enquiries'
    | '/dashboard/jeweller/feeds'
    | '/dashboard/jeweller/markup'
    | '/dashboard/stones/$id'
    | '/dashboard/stones/new'
    | '/dashboard/jeweller/'
    | '/dashboard/stones/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/login'
    | '/marketplace'
    | '/pending-approval'
    | '/sitemap.xml'
    | '/dashboard/enquiries'
    | '/dashboard/import'
    | '/embed/$key'
    | '/sign-up/dealer'
    | '/sign-up/jeweller'
    | '/stone/$id'
    | '/vendors/$slug'
    | '/dashboard'
    | '/vendors'
    | '/api/public/chaos.js'
    | '/api/public/feed'
    | '/dashboard/jeweller/api'
    | '/dashboard/jeweller/enquiries'
    | '/dashboard/jeweller/feeds'
    | '/dashboard/jeweller/markup'
    | '/dashboard/stones/$id'
    | '/dashboard/stones/new'
    | '/dashboard/jeweller'
    | '/dashboard/stones'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/marketplace'
    | '/pending-approval'
    | '/sitemap.xml'
    | '/dashboard/enquiries'
    | '/dashboard/import'
    | '/embed/$key'
    | '/sign-up/dealer'
    | '/sign-up/jeweller'
    | '/stone/$id'
    | '/vendors/$slug'
    | '/dashboard/'
    | '/vendors/'
    | '/api/public/chaos.js'
    | '/api/public/feed'
    | '/dashboard/jeweller/api'
    | '/dashboard/jeweller/enquiries'
    | '/dashboard/jeweller/feeds'
    | '/dashboard/jeweller/markup'
    | '/dashboard/stones/$id'
    | '/dashboard/stones/new'
    | '/dashboard/jeweller/'
    | '/dashboard/stones/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  EmbedKeyRoute: typeof EmbedKeyRoute
  SignUpDealerRoute: typeof SignUpDealerRoute
  SignUpJewellerRoute: typeof SignUpJewellerRoute
  StoneIdRoute: typeof StoneIdRoute
  VendorsSlugRoute: typeof VendorsSlugRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
  ApiPublicChaosDotjsRoute: typeof ApiPublicChaosDotjsRoute
  ApiPublicFeedRoute: typeof ApiPublicFeedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/vendors/$slug': {
      id: '/vendors/$slug'
      path: '/vendors/$slug'
      fullPath: '/vendors/$slug'
      preLoaderRoute: typeof VendorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stone/$id': {
      id: '/stone/$id'
      path: '/stone/$id'
      fullPath: '/stone/$id'
      preLoaderRoute: typeof StoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/jeweller': {
      id: '/sign-up/jeweller'
      path: '/sign-up/jeweller'
      fullPath: '/sign-up/jeweller'
      preLoaderRoute: typeof SignUpJewellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/dealer': {
      id: '/sign-up/dealer'
      path: '/sign-up/dealer'
      fullPath: '/sign-up/dealer'
      preLoaderRoute: typeof SignUpDealerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$key': {
      id: '/embed/$key'
      path: '/embed/$key'
      fullPath: '/embed/$key'
      preLoaderRoute: typeof EmbedKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enquiries': {
      id: '/dashboard/enquiries'
      path: '/enquiries'
      fullPath: '/dashboard/enquiries'
      preLoaderRoute: typeof DashboardEnquiriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stones/': {
      id: '/dashboard/stones/'
      path: '/stones'
      fullPath: '/dashboard/stones/'
      preLoaderRoute: typeof DashboardStonesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/': {
      id: '/dashboard/jeweller/'
      path: '/jeweller'
      fullPath: '/dashboard/jeweller/'
      preLoaderRoute: typeof DashboardJewellerIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stones/new': {
      id: '/dashboard/stones/new'
      path: '/stones/new'
      fullPath: '/dashboard/stones/new'
      preLoaderRoute: typeof DashboardStonesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stones/$id': {
      id: '/dashboard/stones/$id'
      path: '/stones/$id'
      fullPath: '/dashboard/stones/$id'
      preLoaderRoute: typeof DashboardStonesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/markup': {
      id: '/dashboard/jeweller/markup'
      path: '/jeweller/markup'
      fullPath: '/dashboard/jeweller/markup'
      preLoaderRoute: typeof DashboardJewellerMarkupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/feeds': {
      id: '/dashboard/jeweller/feeds'
      path: '/jeweller/feeds'
      fullPath: '/dashboard/jeweller/feeds'
      preLoaderRoute: typeof DashboardJewellerFeedsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/enquiries': {
      id: '/dashboard/jeweller/enquiries'
      path: '/jeweller/enquiries'
      fullPath: '/dashboard/jeweller/enquiries'
      preLoaderRoute: typeof DashboardJewellerEnquiriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/api': {
      id: '/dashboard/jeweller/api'
      path: '/jeweller/api'
      fullPath: '/dashboard/jeweller/api'
      preLoaderRoute: typeof DashboardJewellerApiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/feed': {
      id: '/api/public/feed'
      path: '/api/public/feed'
      fullPath: '/api/public/feed'
      preLoaderRoute: typeof ApiPublicFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chaos.js': {
      id: '/api/public/chaos.js'
      path: '/api/public/chaos.js'
      fullPath: '/api/public/chaos.js'
      preLoaderRoute: typeof ApiPublicChaosDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardEnquiriesRoute: typeof DashboardEnquiriesRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardJewellerApiRoute: typeof DashboardJewellerApiRoute
  DashboardJewellerEnquiriesRoute: typeof DashboardJewellerEnquiriesRoute
  DashboardJewellerFeedsRoute: typeof DashboardJewellerFeedsRoute
  DashboardJewellerMarkupRoute: typeof DashboardJewellerMarkupRoute
  DashboardStonesIdRoute: typeof DashboardStonesIdRoute
  DashboardStonesNewRoute: typeof DashboardStonesNewRoute
  DashboardJewellerIndexRoute: typeof DashboardJewellerIndexRoute
  DashboardStonesIndexRoute: typeof DashboardStonesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardEnquiriesRoute: DashboardEnquiriesRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardJewellerApiRoute: DashboardJewellerApiRoute,
  DashboardJewellerEnquiriesRoute: DashboardJewellerEnquiriesRoute,
  DashboardJewellerFeedsRoute: DashboardJewellerFeedsRoute,
  DashboardJewellerMarkupRoute: DashboardJewellerMarkupRoute,
  DashboardStonesIdRoute: DashboardStonesIdRoute,
  DashboardStonesNewRoute: DashboardStonesNewRoute,
  DashboardJewellerIndexRoute: DashboardJewellerIndexRoute,
  DashboardStonesIndexRoute: DashboardStonesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  EmbedKeyRoute: EmbedKeyRoute,
  SignUpDealerRoute: SignUpDealerRoute,
  SignUpJewellerRoute: SignUpJewellerRoute,
  StoneIdRoute: StoneIdRoute,
  VendorsSlugRoute: VendorsSlugRoute,
  VendorsIndexRoute: VendorsIndexRoute,
  ApiPublicChaosDotjsRoute: ApiPublicChaosDotjsRoute,
  ApiPublicFeedRoute: ApiPublicFeedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
