/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as RetailRouteImport } from './routes/retail'
import { Route as RequestsRouteImport } from './routes/requests'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VendorsIndexRouteImport } from './routes/vendors.index'
import { Route as SignUpIndexRouteImport } from './routes/sign-up.index'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as JewellersIndexRouteImport } from './routes/jewellers.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VendorsSlugRouteImport } from './routes/vendors.$slug'
import { Route as StoneIdRouteImport } from './routes/stone.$id'
import { Route as SignUpJewellerRouteImport } from './routes/sign-up.jeweller'
import { Route as SignUpDealerRouteImport } from './routes/sign-up.dealer'
import { Route as MarketplaceSlugRouteImport } from './routes/marketplace.$slug'
import { Route as LegalTermsJewellersRouteImport } from './routes/legal.terms-jewellers'
import { Route as LegalTermsDealersRouteImport } from './routes/legal.terms-dealers'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as JewellersSlugRouteImport } from './routes/jewellers.$slug'
import { Route as HowItWorksShippingRouteImport } from './routes/how-it-works.shipping'
import { Route as HowItWorksPaymentsRouteImport } from './routes/how-it-works.payments'
import { Route as EmbedKeyRouteImport } from './routes/embed.$key'
import { Route as DocsDealerApiRouteImport } from './routes/docs.dealer-api'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as DashboardSalesRouteImport } from './routes/dashboard.sales'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardImportRouteImport } from './routes/dashboard.import'
import { Route as DashboardEnquiriesRouteImport } from './routes/dashboard.enquiries'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as AdminRequestsRouteImport } from './routes/admin.requests'
import { Route as AdminQuickApproveRouteImport } from './routes/admin.quick-approve'
import { Route as AdminImportTestRouteImport } from './routes/admin.import-test'
import { Route as DashboardStonesIndexRouteImport } from './routes/dashboard.stones.index'
import { Route as DashboardJewellerIndexRouteImport } from './routes/dashboard.jeweller.index'
import { Route as LearnGemstonesTypeRouteImport } from './routes/learn.gemstones.$type'
import { Route as DashboardStonesNewRouteImport } from './routes/dashboard.stones.new'
import { Route as DashboardStonesIdRouteImport } from './routes/dashboard.stones.$id'
import { Route as DashboardJewellerWishlistRouteImport } from './routes/dashboard.jeweller.wishlist'
import { Route as DashboardJewellerShopifyRouteImport } from './routes/dashboard.jeweller.shopify'
import { Route as DashboardJewellerSavedSearchesRouteImport } from './routes/dashboard.jeweller.saved-searches'
import { Route as DashboardJewellerOrdersRouteImport } from './routes/dashboard.jeweller.orders'
import { Route as DashboardJewellerMarkupRouteImport } from './routes/dashboard.jeweller.markup'
import { Route as DashboardJewellerFeedsRouteImport } from './routes/dashboard.jeweller.feeds'
import { Route as DashboardJewellerEnquiriesRouteImport } from './routes/dashboard.jeweller.enquiries'
import { Route as DashboardJewellerApiRouteImport } from './routes/dashboard.jeweller.api'
import { Route as DashboardDealerWhatsappRouteImport } from './routes/dashboard.dealer.whatsapp'
import { Route as DashboardDealerPricingRouteImport } from './routes/dashboard.dealer.pricing'
import { Route as DashboardDealerApiRouteImport } from './routes/dashboard.dealer.api'
import { Route as ApiPublicFeedRouteImport } from './routes/api/public/feed'
import { Route as ApiPublicChaosDotjsRouteImport } from './routes/api/public/chaos[.]js'
import { Route as AdminDealerIdRouteImport } from './routes/admin.dealer.$id'
import { Route as ApiPublicCronShopifySyncRouteImport } from './routes/api/public/cron/shopify-sync'
import { Route as ApiPublicCronSavedSearchDigestRouteImport } from './routes/api/public/cron/saved-search-digest'
import { Route as ApiPublicCronDigestRouteImport } from './routes/api/public/cron/digest'
import { Route as ApiPublicAdminQuickApproveRouteImport } from './routes/api/public/admin/quick-approve'
import { Route as ApiDealerV1StonesRouteImport } from './routes/api/dealer/v1/stones'
import { Route as ApiPublicHooksShopifyEventsRouteImport } from './routes/api/public/hooks/shopify/events'
import { Route as ApiPublicHooksEmailNotifyRouteImport } from './routes/api/public/hooks/email/notify'
import { Route as ApiDealerV1StonesBulkRouteImport } from './routes/api/dealer/v1/stones/bulk'
import { Route as ApiDealerV1StonesIdRouteImport } from './routes/api/dealer/v1/stones/$id'
import { Route as AdminDealerIdStonesNewRouteImport } from './routes/admin.dealer.$id.stones.new'
import { Route as ApiDealerV1StonesIdMarkSoldRouteImport } from './routes/api/dealer/v1/stones/$id/mark-sold'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailRoute = RetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsIndexRoute = VendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const JewellersIndexRoute = JewellersIndexRouteImport.update({
  id: '/jewellers/',
  path: '/jewellers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const VendorsSlugRoute = VendorsSlugRouteImport.update({
  id: '/vendors/$slug',
  path: '/vendors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const StoneIdRoute = StoneIdRouteImport.update({
  id: '/stone/$id',
  path: '/stone/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpJewellerRoute = SignUpJewellerRouteImport.update({
  id: '/sign-up/jeweller',
  path: '/sign-up/jeweller',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpDealerRoute = SignUpDealerRouteImport.update({
  id: '/sign-up/dealer',
  path: '/sign-up/dealer',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceSlugRoute = MarketplaceSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => MarketplaceRoute,
} as any)
const LegalTermsJewellersRoute = LegalTermsJewellersRouteImport.update({
  id: '/legal/terms-jewellers',
  path: '/legal/terms-jewellers',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsDealersRoute = LegalTermsDealersRouteImport.update({
  id: '/legal/terms-dealers',
  path: '/legal/terms-dealers',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const JewellersSlugRoute = JewellersSlugRouteImport.update({
  id: '/jewellers/$slug',
  path: '/jewellers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksShippingRoute = HowItWorksShippingRouteImport.update({
  id: '/how-it-works/shipping',
  path: '/how-it-works/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksPaymentsRoute = HowItWorksPaymentsRouteImport.update({
  id: '/how-it-works/payments',
  path: '/how-it-works/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedKeyRoute = EmbedKeyRouteImport.update({
  id: '/embed/$key',
  path: '/embed/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDealerApiRoute = DocsDealerApiRouteImport.update({
  id: '/docs/dealer-api',
  path: '/docs/dealer-api',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSalesRoute = DashboardSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardImportRoute = DashboardImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEnquiriesRoute = DashboardEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQuickApproveRoute = AdminQuickApproveRouteImport.update({
  id: '/quick-approve',
  path: '/quick-approve',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImportTestRoute = AdminImportTestRouteImport.update({
  id: '/import-test',
  path: '/import-test',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardStonesIndexRoute = DashboardStonesIndexRouteImport.update({
  id: '/stones/',
  path: '/stones/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJewellerIndexRoute = DashboardJewellerIndexRouteImport.update({
  id: '/jeweller/',
  path: '/jeweller/',
  getParentRoute: () => DashboardRoute,
} as any)
const LearnGemstonesTypeRoute = LearnGemstonesTypeRouteImport.update({
  id: '/learn/gemstones/$type',
  path: '/learn/gemstones/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStonesNewRoute = DashboardStonesNewRouteImport.update({
  id: '/stones/new',
  path: '/stones/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStonesIdRoute = DashboardStonesIdRouteImport.update({
  id: '/stones/$id',
  path: '/stones/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJewellerWishlistRoute =
  DashboardJewellerWishlistRouteImport.update({
    id: '/jeweller/wishlist',
    path: '/jeweller/wishlist',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardJewellerShopifyRoute =
  DashboardJewellerShopifyRouteImport.update({
    id: '/jeweller/shopify',
    path: '/jeweller/shopify',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardJewellerSavedSearchesRoute =
  DashboardJewellerSavedSearchesRouteImport.update({
    id: '/jeweller/saved-searches',
    path: '/jeweller/saved-searches',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardJewellerOrdersRoute = DashboardJewellerOrdersRouteImport.update({
  id: '/jeweller/orders',
  path: '/jeweller/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJewellerMarkupRoute = DashboardJewellerMarkupRouteImport.update({
  id: '/jeweller/markup',
  path: '/jeweller/markup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJewellerFeedsRoute = DashboardJewellerFeedsRouteImport.update({
  id: '/jeweller/feeds',
  path: '/jeweller/feeds',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJewellerEnquiriesRoute =
  DashboardJewellerEnquiriesRouteImport.update({
    id: '/jeweller/enquiries',
    path: '/jeweller/enquiries',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardJewellerApiRoute = DashboardJewellerApiRouteImport.update({
  id: '/jeweller/api',
  path: '/jeweller/api',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDealerWhatsappRoute = DashboardDealerWhatsappRouteImport.update({
  id: '/dealer/whatsapp',
  path: '/dealer/whatsapp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDealerPricingRoute = DashboardDealerPricingRouteImport.update({
  id: '/dealer/pricing',
  path: '/dealer/pricing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDealerApiRoute = DashboardDealerApiRouteImport.update({
  id: '/dealer/api',
  path: '/dealer/api',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiPublicFeedRoute = ApiPublicFeedRouteImport.update({
  id: '/api/public/feed',
  path: '/api/public/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChaosDotjsRoute = ApiPublicChaosDotjsRouteImport.update({
  id: '/api/public/chaos.js',
  path: '/api/public/chaos.js',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDealerIdRoute = AdminDealerIdRouteImport.update({
  id: '/dealer/$id',
  path: '/dealer/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicCronShopifySyncRoute =
  ApiPublicCronShopifySyncRouteImport.update({
    id: '/api/public/cron/shopify-sync',
    path: '/api/public/cron/shopify-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSavedSearchDigestRoute =
  ApiPublicCronSavedSearchDigestRouteImport.update({
    id: '/api/public/cron/saved-search-digest',
    path: '/api/public/cron/saved-search-digest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDigestRoute = ApiPublicCronDigestRouteImport.update({
  id: '/api/public/cron/digest',
  path: '/api/public/cron/digest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminQuickApproveRoute =
  ApiPublicAdminQuickApproveRouteImport.update({
    id: '/api/public/admin/quick-approve',
    path: '/api/public/admin/quick-approve',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDealerV1StonesRoute = ApiDealerV1StonesRouteImport.update({
  id: '/api/dealer/v1/stones',
  path: '/api/dealer/v1/stones',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksShopifyEventsRoute =
  ApiPublicHooksShopifyEventsRouteImport.update({
    id: '/api/public/hooks/shopify/events',
    path: '/api/public/hooks/shopify/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailNotifyRoute =
  ApiPublicHooksEmailNotifyRouteImport.update({
    id: '/api/public/hooks/email/notify',
    path: '/api/public/hooks/email/notify',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDealerV1StonesBulkRoute = ApiDealerV1StonesBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => ApiDealerV1StonesRoute,
} as any)
const ApiDealerV1StonesIdRoute = ApiDealerV1StonesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiDealerV1StonesRoute,
} as any)
const AdminDealerIdStonesNewRoute = AdminDealerIdStonesNewRouteImport.update({
  id: '/stones/new',
  path: '/stones/new',
  getParentRoute: () => AdminDealerIdRoute,
} as any)
const ApiDealerV1StonesIdMarkSoldRoute =
  ApiDealerV1StonesIdMarkSoldRouteImport.update({
    id: '/mark-sold',
    path: '/mark-sold',
    getParentRoute: () => ApiDealerV1StonesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/pending-approval': typeof PendingApprovalRoute
  '/requests': typeof RequestsRoute
  '/retail': typeof RetailRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/import-test': typeof AdminImportTestRoute
  '/admin/quick-approve': typeof AdminQuickApproveRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/dealer-api': typeof DocsDealerApiRoute
  '/embed/$key': typeof EmbedKeyRoute
  '/how-it-works/payments': typeof HowItWorksPaymentsRoute
  '/how-it-works/shipping': typeof HowItWorksShippingRoute
  '/jewellers/$slug': typeof JewellersSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms-dealers': typeof LegalTermsDealersRoute
  '/legal/terms-jewellers': typeof LegalTermsJewellersRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/sign-up/dealer': typeof SignUpDealerRoute
  '/sign-up/jeweller': typeof SignUpJewellerRoute
  '/stone/$id': typeof StoneIdRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/jewellers/': typeof JewellersIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/admin/dealer/$id': typeof AdminDealerIdRouteWithChildren
  '/api/public/chaos.js': typeof ApiPublicChaosDotjsRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
  '/dashboard/dealer/api': typeof DashboardDealerApiRoute
  '/dashboard/dealer/pricing': typeof DashboardDealerPricingRoute
  '/dashboard/dealer/whatsapp': typeof DashboardDealerWhatsappRoute
  '/dashboard/jeweller/api': typeof DashboardJewellerApiRoute
  '/dashboard/jeweller/enquiries': typeof DashboardJewellerEnquiriesRoute
  '/dashboard/jeweller/feeds': typeof DashboardJewellerFeedsRoute
  '/dashboard/jeweller/markup': typeof DashboardJewellerMarkupRoute
  '/dashboard/jeweller/orders': typeof DashboardJewellerOrdersRoute
  '/dashboard/jeweller/saved-searches': typeof DashboardJewellerSavedSearchesRoute
  '/dashboard/jeweller/shopify': typeof DashboardJewellerShopifyRoute
  '/dashboard/jeweller/wishlist': typeof DashboardJewellerWishlistRoute
  '/dashboard/stones/$id': typeof DashboardStonesIdRoute
  '/dashboard/stones/new': typeof DashboardStonesNewRoute
  '/learn/gemstones/$type': typeof LearnGemstonesTypeRoute
  '/dashboard/jeweller/': typeof DashboardJewellerIndexRoute
  '/dashboard/stones/': typeof DashboardStonesIndexRoute
  '/api/dealer/v1/stones': typeof ApiDealerV1StonesRouteWithChildren
  '/api/public/admin/quick-approve': typeof ApiPublicAdminQuickApproveRoute
  '/api/public/cron/digest': typeof ApiPublicCronDigestRoute
  '/api/public/cron/saved-search-digest': typeof ApiPublicCronSavedSearchDigestRoute
  '/api/public/cron/shopify-sync': typeof ApiPublicCronShopifySyncRoute
  '/admin/dealer/$id/stones/new': typeof AdminDealerIdStonesNewRoute
  '/api/dealer/v1/stones/$id': typeof ApiDealerV1StonesIdRouteWithChildren
  '/api/dealer/v1/stones/bulk': typeof ApiDealerV1StonesBulkRoute
  '/api/public/hooks/email/notify': typeof ApiPublicHooksEmailNotifyRoute
  '/api/public/hooks/shopify/events': typeof ApiPublicHooksShopifyEventsRoute
  '/api/dealer/v1/stones/$id/mark-sold': typeof ApiDealerV1StonesIdMarkSoldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/compare': typeof CompareRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/pending-approval': typeof PendingApprovalRoute
  '/requests': typeof RequestsRoute
  '/retail': typeof RetailRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/import-test': typeof AdminImportTestRoute
  '/admin/quick-approve': typeof AdminQuickApproveRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/dealer-api': typeof DocsDealerApiRoute
  '/embed/$key': typeof EmbedKeyRoute
  '/how-it-works/payments': typeof HowItWorksPaymentsRoute
  '/how-it-works/shipping': typeof HowItWorksShippingRoute
  '/jewellers/$slug': typeof JewellersSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms-dealers': typeof LegalTermsDealersRoute
  '/legal/terms-jewellers': typeof LegalTermsJewellersRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/sign-up/dealer': typeof SignUpDealerRoute
  '/sign-up/jeweller': typeof SignUpJewellerRoute
  '/stone/$id': typeof StoneIdRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/dashboard': typeof DashboardIndexRoute
  '/jewellers': typeof JewellersIndexRoute
  '/learn': typeof LearnIndexRoute
  '/sign-up': typeof SignUpIndexRoute
  '/vendors': typeof VendorsIndexRoute
  '/admin/dealer/$id': typeof AdminDealerIdRouteWithChildren
  '/api/public/chaos.js': typeof ApiPublicChaosDotjsRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
  '/dashboard/dealer/api': typeof DashboardDealerApiRoute
  '/dashboard/dealer/pricing': typeof DashboardDealerPricingRoute
  '/dashboard/dealer/whatsapp': typeof DashboardDealerWhatsappRoute
  '/dashboard/jeweller/api': typeof DashboardJewellerApiRoute
  '/dashboard/jeweller/enquiries': typeof DashboardJewellerEnquiriesRoute
  '/dashboard/jeweller/feeds': typeof DashboardJewellerFeedsRoute
  '/dashboard/jeweller/markup': typeof DashboardJewellerMarkupRoute
  '/dashboard/jeweller/orders': typeof DashboardJewellerOrdersRoute
  '/dashboard/jeweller/saved-searches': typeof DashboardJewellerSavedSearchesRoute
  '/dashboard/jeweller/shopify': typeof DashboardJewellerShopifyRoute
  '/dashboard/jeweller/wishlist': typeof DashboardJewellerWishlistRoute
  '/dashboard/stones/$id': typeof DashboardStonesIdRoute
  '/dashboard/stones/new': typeof DashboardStonesNewRoute
  '/learn/gemstones/$type': typeof LearnGemstonesTypeRoute
  '/dashboard/jeweller': typeof DashboardJewellerIndexRoute
  '/dashboard/stones': typeof DashboardStonesIndexRoute
  '/api/dealer/v1/stones': typeof ApiDealerV1StonesRouteWithChildren
  '/api/public/admin/quick-approve': typeof ApiPublicAdminQuickApproveRoute
  '/api/public/cron/digest': typeof ApiPublicCronDigestRoute
  '/api/public/cron/saved-search-digest': typeof ApiPublicCronSavedSearchDigestRoute
  '/api/public/cron/shopify-sync': typeof ApiPublicCronShopifySyncRoute
  '/admin/dealer/$id/stones/new': typeof AdminDealerIdStonesNewRoute
  '/api/dealer/v1/stones/$id': typeof ApiDealerV1StonesIdRouteWithChildren
  '/api/dealer/v1/stones/bulk': typeof ApiDealerV1StonesBulkRoute
  '/api/public/hooks/email/notify': typeof ApiPublicHooksEmailNotifyRoute
  '/api/public/hooks/shopify/events': typeof ApiPublicHooksShopifyEventsRoute
  '/api/dealer/v1/stones/$id/mark-sold': typeof ApiDealerV1StonesIdMarkSoldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/pending-approval': typeof PendingApprovalRoute
  '/requests': typeof RequestsRoute
  '/retail': typeof RetailRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/import-test': typeof AdminImportTestRoute
  '/admin/quick-approve': typeof AdminQuickApproveRoute
  '/admin/requests': typeof AdminRequestsRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/enquiries': typeof DashboardEnquiriesRoute
  '/dashboard/import': typeof DashboardImportRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/dashboard/sales': typeof DashboardSalesRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/dealer-api': typeof DocsDealerApiRoute
  '/embed/$key': typeof EmbedKeyRoute
  '/how-it-works/payments': typeof HowItWorksPaymentsRoute
  '/how-it-works/shipping': typeof HowItWorksShippingRoute
  '/jewellers/$slug': typeof JewellersSlugRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms-dealers': typeof LegalTermsDealersRoute
  '/legal/terms-jewellers': typeof LegalTermsJewellersRoute
  '/marketplace/$slug': typeof MarketplaceSlugRoute
  '/sign-up/dealer': typeof SignUpDealerRoute
  '/sign-up/jeweller': typeof SignUpJewellerRoute
  '/stone/$id': typeof StoneIdRoute
  '/vendors/$slug': typeof VendorsSlugRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/jewellers/': typeof JewellersIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/sign-up/': typeof SignUpIndexRoute
  '/vendors/': typeof VendorsIndexRoute
  '/admin/dealer/$id': typeof AdminDealerIdRouteWithChildren
  '/api/public/chaos.js': typeof ApiPublicChaosDotjsRoute
  '/api/public/feed': typeof ApiPublicFeedRoute
  '/dashboard/dealer/api': typeof DashboardDealerApiRoute
  '/dashboard/dealer/pricing': typeof DashboardDealerPricingRoute
  '/dashboard/dealer/whatsapp': typeof DashboardDealerWhatsappRoute
  '/dashboard/jeweller/api': typeof DashboardJewellerApiRoute
  '/dashboard/jeweller/enquiries': typeof DashboardJewellerEnquiriesRoute
  '/dashboard/jeweller/feeds': typeof DashboardJewellerFeedsRoute
  '/dashboard/jeweller/markup': typeof DashboardJewellerMarkupRoute
  '/dashboard/jeweller/orders': typeof DashboardJewellerOrdersRoute
  '/dashboard/jeweller/saved-searches': typeof DashboardJewellerSavedSearchesRoute
  '/dashboard/jeweller/shopify': typeof DashboardJewellerShopifyRoute
  '/dashboard/jeweller/wishlist': typeof DashboardJewellerWishlistRoute
  '/dashboard/stones/$id': typeof DashboardStonesIdRoute
  '/dashboard/stones/new': typeof DashboardStonesNewRoute
  '/learn/gemstones/$type': typeof LearnGemstonesTypeRoute
  '/dashboard/jeweller/': typeof DashboardJewellerIndexRoute
  '/dashboard/stones/': typeof DashboardStonesIndexRoute
  '/api/dealer/v1/stones': typeof ApiDealerV1StonesRouteWithChildren
  '/api/public/admin/quick-approve': typeof ApiPublicAdminQuickApproveRoute
  '/api/public/cron/digest': typeof ApiPublicCronDigestRoute
  '/api/public/cron/saved-search-digest': typeof ApiPublicCronSavedSearchDigestRoute
  '/api/public/cron/shopify-sync': typeof ApiPublicCronShopifySyncRoute
  '/admin/dealer/$id/stones/new': typeof AdminDealerIdStonesNewRoute
  '/api/dealer/v1/stones/$id': typeof ApiDealerV1StonesIdRouteWithChildren
  '/api/dealer/v1/stones/bulk': typeof ApiDealerV1StonesBulkRoute
  '/api/public/hooks/email/notify': typeof ApiPublicHooksEmailNotifyRoute
  '/api/public/hooks/shopify/events': typeof ApiPublicHooksShopifyEventsRoute
  '/api/dealer/v1/stones/$id/mark-sold': typeof ApiDealerV1StonesIdMarkSoldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/compare'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/marketplace'
    | '/pending-approval'
    | '/requests'
    | '/retail'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/import-test'
    | '/admin/quick-approve'
    | '/admin/requests'
    | '/dashboard/account'
    | '/dashboard/enquiries'
    | '/dashboard/import'
    | '/dashboard/referrals'
    | '/dashboard/sales'
    | '/docs/api'
    | '/docs/dealer-api'
    | '/embed/$key'
    | '/how-it-works/payments'
    | '/how-it-works/shipping'
    | '/jewellers/$slug'
    | '/learn/$slug'
    | '/legal/privacy'
    | '/legal/terms-dealers'
    | '/legal/terms-jewellers'
    | '/marketplace/$slug'
    | '/sign-up/dealer'
    | '/sign-up/jeweller'
    | '/stone/$id'
    | '/vendors/$slug'
    | '/dashboard/'
    | '/jewellers/'
    | '/learn/'
    | '/sign-up/'
    | '/vendors/'
    | '/admin/dealer/$id'
    | '/api/public/chaos.js'
    | '/api/public/feed'
    | '/dashboard/dealer/api'
    | '/dashboard/dealer/pricing'
    | '/dashboard/dealer/whatsapp'
    | '/dashboard/jeweller/api'
    | '/dashboard/jeweller/enquiries'
    | '/dashboard/jeweller/feeds'
    | '/dashboard/jeweller/markup'
    | '/dashboard/jeweller/orders'
    | '/dashboard/jeweller/saved-searches'
    | '/dashboard/jeweller/shopify'
    | '/dashboard/jeweller/wishlist'
    | '/dashboard/stones/$id'
    | '/dashboard/stones/new'
    | '/learn/gemstones/$type'
    | '/dashboard/jeweller/'
    | '/dashboard/stones/'
    | '/api/dealer/v1/stones'
    | '/api/public/admin/quick-approve'
    | '/api/public/cron/digest'
    | '/api/public/cron/saved-search-digest'
    | '/api/public/cron/shopify-sync'
    | '/admin/dealer/$id/stones/new'
    | '/api/dealer/v1/stones/$id'
    | '/api/dealer/v1/stones/bulk'
    | '/api/public/hooks/email/notify'
    | '/api/public/hooks/shopify/events'
    | '/api/dealer/v1/stones/$id/mark-sold'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/compare'
    | '/faq'
    | '/login'
    | '/marketplace'
    | '/pending-approval'
    | '/requests'
    | '/retail'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/import-test'
    | '/admin/quick-approve'
    | '/admin/requests'
    | '/dashboard/account'
    | '/dashboard/enquiries'
    | '/dashboard/import'
    | '/dashboard/referrals'
    | '/dashboard/sales'
    | '/docs/api'
    | '/docs/dealer-api'
    | '/embed/$key'
    | '/how-it-works/payments'
    | '/how-it-works/shipping'
    | '/jewellers/$slug'
    | '/learn/$slug'
    | '/legal/privacy'
    | '/legal/terms-dealers'
    | '/legal/terms-jewellers'
    | '/marketplace/$slug'
    | '/sign-up/dealer'
    | '/sign-up/jeweller'
    | '/stone/$id'
    | '/vendors/$slug'
    | '/dashboard'
    | '/jewellers'
    | '/learn'
    | '/sign-up'
    | '/vendors'
    | '/admin/dealer/$id'
    | '/api/public/chaos.js'
    | '/api/public/feed'
    | '/dashboard/dealer/api'
    | '/dashboard/dealer/pricing'
    | '/dashboard/dealer/whatsapp'
    | '/dashboard/jeweller/api'
    | '/dashboard/jeweller/enquiries'
    | '/dashboard/jeweller/feeds'
    | '/dashboard/jeweller/markup'
    | '/dashboard/jeweller/orders'
    | '/dashboard/jeweller/saved-searches'
    | '/dashboard/jeweller/shopify'
    | '/dashboard/jeweller/wishlist'
    | '/dashboard/stones/$id'
    | '/dashboard/stones/new'
    | '/learn/gemstones/$type'
    | '/dashboard/jeweller'
    | '/dashboard/stones'
    | '/api/dealer/v1/stones'
    | '/api/public/admin/quick-approve'
    | '/api/public/cron/digest'
    | '/api/public/cron/saved-search-digest'
    | '/api/public/cron/shopify-sync'
    | '/admin/dealer/$id/stones/new'
    | '/api/dealer/v1/stones/$id'
    | '/api/dealer/v1/stones/bulk'
    | '/api/public/hooks/email/notify'
    | '/api/public/hooks/shopify/events'
    | '/api/dealer/v1/stones/$id/mark-sold'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/compare'
    | '/dashboard'
    | '/faq'
    | '/login'
    | '/marketplace'
    | '/pending-approval'
    | '/requests'
    | '/retail'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/import-test'
    | '/admin/quick-approve'
    | '/admin/requests'
    | '/dashboard/account'
    | '/dashboard/enquiries'
    | '/dashboard/import'
    | '/dashboard/referrals'
    | '/dashboard/sales'
    | '/docs/api'
    | '/docs/dealer-api'
    | '/embed/$key'
    | '/how-it-works/payments'
    | '/how-it-works/shipping'
    | '/jewellers/$slug'
    | '/learn/$slug'
    | '/legal/privacy'
    | '/legal/terms-dealers'
    | '/legal/terms-jewellers'
    | '/marketplace/$slug'
    | '/sign-up/dealer'
    | '/sign-up/jeweller'
    | '/stone/$id'
    | '/vendors/$slug'
    | '/dashboard/'
    | '/jewellers/'
    | '/learn/'
    | '/sign-up/'
    | '/vendors/'
    | '/admin/dealer/$id'
    | '/api/public/chaos.js'
    | '/api/public/feed'
    | '/dashboard/dealer/api'
    | '/dashboard/dealer/pricing'
    | '/dashboard/dealer/whatsapp'
    | '/dashboard/jeweller/api'
    | '/dashboard/jeweller/enquiries'
    | '/dashboard/jeweller/feeds'
    | '/dashboard/jeweller/markup'
    | '/dashboard/jeweller/orders'
    | '/dashboard/jeweller/saved-searches'
    | '/dashboard/jeweller/shopify'
    | '/dashboard/jeweller/wishlist'
    | '/dashboard/stones/$id'
    | '/dashboard/stones/new'
    | '/learn/gemstones/$type'
    | '/dashboard/jeweller/'
    | '/dashboard/stones/'
    | '/api/dealer/v1/stones'
    | '/api/public/admin/quick-approve'
    | '/api/public/cron/digest'
    | '/api/public/cron/saved-search-digest'
    | '/api/public/cron/shopify-sync'
    | '/admin/dealer/$id/stones/new'
    | '/api/dealer/v1/stones/$id'
    | '/api/dealer/v1/stones/bulk'
    | '/api/public/hooks/email/notify'
    | '/api/public/hooks/shopify/events'
    | '/api/dealer/v1/stones/$id/mark-sold'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  PendingApprovalRoute: typeof PendingApprovalRoute
  RequestsRoute: typeof RequestsRoute
  RetailRoute: typeof RetailRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DocsApiRoute: typeof DocsApiRoute
  DocsDealerApiRoute: typeof DocsDealerApiRoute
  EmbedKeyRoute: typeof EmbedKeyRoute
  HowItWorksPaymentsRoute: typeof HowItWorksPaymentsRoute
  HowItWorksShippingRoute: typeof HowItWorksShippingRoute
  JewellersSlugRoute: typeof JewellersSlugRoute
  LearnSlugRoute: typeof LearnSlugRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsDealersRoute: typeof LegalTermsDealersRoute
  LegalTermsJewellersRoute: typeof LegalTermsJewellersRoute
  SignUpDealerRoute: typeof SignUpDealerRoute
  SignUpJewellerRoute: typeof SignUpJewellerRoute
  StoneIdRoute: typeof StoneIdRoute
  VendorsSlugRoute: typeof VendorsSlugRoute
  JewellersIndexRoute: typeof JewellersIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  SignUpIndexRoute: typeof SignUpIndexRoute
  VendorsIndexRoute: typeof VendorsIndexRoute
  ApiPublicChaosDotjsRoute: typeof ApiPublicChaosDotjsRoute
  ApiPublicFeedRoute: typeof ApiPublicFeedRoute
  LearnGemstonesTypeRoute: typeof LearnGemstonesTypeRoute
  ApiDealerV1StonesRoute: typeof ApiDealerV1StonesRouteWithChildren
  ApiPublicAdminQuickApproveRoute: typeof ApiPublicAdminQuickApproveRoute
  ApiPublicCronDigestRoute: typeof ApiPublicCronDigestRoute
  ApiPublicCronSavedSearchDigestRoute: typeof ApiPublicCronSavedSearchDigestRoute
  ApiPublicCronShopifySyncRoute: typeof ApiPublicCronShopifySyncRoute
  ApiPublicHooksEmailNotifyRoute: typeof ApiPublicHooksEmailNotifyRoute
  ApiPublicHooksShopifyEventsRoute: typeof ApiPublicHooksShopifyEventsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retail': {
      id: '/retail'
      path: '/retail'
      fullPath: '/retail'
      preLoaderRoute: typeof RetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors/': {
      id: '/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof VendorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/': {
      id: '/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof SignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellers/': {
      id: '/jewellers/'
      path: '/jewellers'
      fullPath: '/jewellers/'
      preLoaderRoute: typeof JewellersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/vendors/$slug': {
      id: '/vendors/$slug'
      path: '/vendors/$slug'
      fullPath: '/vendors/$slug'
      preLoaderRoute: typeof VendorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stone/$id': {
      id: '/stone/$id'
      path: '/stone/$id'
      fullPath: '/stone/$id'
      preLoaderRoute: typeof StoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/jeweller': {
      id: '/sign-up/jeweller'
      path: '/sign-up/jeweller'
      fullPath: '/sign-up/jeweller'
      preLoaderRoute: typeof SignUpJewellerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/dealer': {
      id: '/sign-up/dealer'
      path: '/sign-up/dealer'
      fullPath: '/sign-up/dealer'
      preLoaderRoute: typeof SignUpDealerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$slug': {
      id: '/marketplace/$slug'
      path: '/$slug'
      fullPath: '/marketplace/$slug'
      preLoaderRoute: typeof MarketplaceSlugRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/legal/terms-jewellers': {
      id: '/legal/terms-jewellers'
      path: '/legal/terms-jewellers'
      fullPath: '/legal/terms-jewellers'
      preLoaderRoute: typeof LegalTermsJewellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms-dealers': {
      id: '/legal/terms-dealers'
      path: '/legal/terms-dealers'
      fullPath: '/legal/terms-dealers'
      preLoaderRoute: typeof LegalTermsDealersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jewellers/$slug': {
      id: '/jewellers/$slug'
      path: '/jewellers/$slug'
      fullPath: '/jewellers/$slug'
      preLoaderRoute: typeof JewellersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works/shipping': {
      id: '/how-it-works/shipping'
      path: '/how-it-works/shipping'
      fullPath: '/how-it-works/shipping'
      preLoaderRoute: typeof HowItWorksShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works/payments': {
      id: '/how-it-works/payments'
      path: '/how-it-works/payments'
      fullPath: '/how-it-works/payments'
      preLoaderRoute: typeof HowItWorksPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed/$key': {
      id: '/embed/$key'
      path: '/embed/$key'
      fullPath: '/embed/$key'
      preLoaderRoute: typeof EmbedKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/dealer-api': {
      id: '/docs/dealer-api'
      path: '/docs/dealer-api'
      fullPath: '/docs/dealer-api'
      preLoaderRoute: typeof DocsDealerApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/sales': {
      id: '/dashboard/sales'
      path: '/sales'
      fullPath: '/dashboard/sales'
      preLoaderRoute: typeof DashboardSalesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/import': {
      id: '/dashboard/import'
      path: '/import'
      fullPath: '/dashboard/import'
      preLoaderRoute: typeof DashboardImportRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/enquiries': {
      id: '/dashboard/enquiries'
      path: '/enquiries'
      fullPath: '/dashboard/enquiries'
      preLoaderRoute: typeof DashboardEnquiriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/requests': {
      id: '/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/quick-approve': {
      id: '/admin/quick-approve'
      path: '/quick-approve'
      fullPath: '/admin/quick-approve'
      preLoaderRoute: typeof AdminQuickApproveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/import-test': {
      id: '/admin/import-test'
      path: '/import-test'
      fullPath: '/admin/import-test'
      preLoaderRoute: typeof AdminImportTestRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/stones/': {
      id: '/dashboard/stones/'
      path: '/stones'
      fullPath: '/dashboard/stones/'
      preLoaderRoute: typeof DashboardStonesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/': {
      id: '/dashboard/jeweller/'
      path: '/jeweller'
      fullPath: '/dashboard/jeweller/'
      preLoaderRoute: typeof DashboardJewellerIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/learn/gemstones/$type': {
      id: '/learn/gemstones/$type'
      path: '/learn/gemstones/$type'
      fullPath: '/learn/gemstones/$type'
      preLoaderRoute: typeof LearnGemstonesTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/stones/new': {
      id: '/dashboard/stones/new'
      path: '/stones/new'
      fullPath: '/dashboard/stones/new'
      preLoaderRoute: typeof DashboardStonesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stones/$id': {
      id: '/dashboard/stones/$id'
      path: '/stones/$id'
      fullPath: '/dashboard/stones/$id'
      preLoaderRoute: typeof DashboardStonesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/wishlist': {
      id: '/dashboard/jeweller/wishlist'
      path: '/jeweller/wishlist'
      fullPath: '/dashboard/jeweller/wishlist'
      preLoaderRoute: typeof DashboardJewellerWishlistRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/shopify': {
      id: '/dashboard/jeweller/shopify'
      path: '/jeweller/shopify'
      fullPath: '/dashboard/jeweller/shopify'
      preLoaderRoute: typeof DashboardJewellerShopifyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/saved-searches': {
      id: '/dashboard/jeweller/saved-searches'
      path: '/jeweller/saved-searches'
      fullPath: '/dashboard/jeweller/saved-searches'
      preLoaderRoute: typeof DashboardJewellerSavedSearchesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/orders': {
      id: '/dashboard/jeweller/orders'
      path: '/jeweller/orders'
      fullPath: '/dashboard/jeweller/orders'
      preLoaderRoute: typeof DashboardJewellerOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/markup': {
      id: '/dashboard/jeweller/markup'
      path: '/jeweller/markup'
      fullPath: '/dashboard/jeweller/markup'
      preLoaderRoute: typeof DashboardJewellerMarkupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/feeds': {
      id: '/dashboard/jeweller/feeds'
      path: '/jeweller/feeds'
      fullPath: '/dashboard/jeweller/feeds'
      preLoaderRoute: typeof DashboardJewellerFeedsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/enquiries': {
      id: '/dashboard/jeweller/enquiries'
      path: '/jeweller/enquiries'
      fullPath: '/dashboard/jeweller/enquiries'
      preLoaderRoute: typeof DashboardJewellerEnquiriesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jeweller/api': {
      id: '/dashboard/jeweller/api'
      path: '/jeweller/api'
      fullPath: '/dashboard/jeweller/api'
      preLoaderRoute: typeof DashboardJewellerApiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dealer/whatsapp': {
      id: '/dashboard/dealer/whatsapp'
      path: '/dealer/whatsapp'
      fullPath: '/dashboard/dealer/whatsapp'
      preLoaderRoute: typeof DashboardDealerWhatsappRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dealer/pricing': {
      id: '/dashboard/dealer/pricing'
      path: '/dealer/pricing'
      fullPath: '/dashboard/dealer/pricing'
      preLoaderRoute: typeof DashboardDealerPricingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/dealer/api': {
      id: '/dashboard/dealer/api'
      path: '/dealer/api'
      fullPath: '/dashboard/dealer/api'
      preLoaderRoute: typeof DashboardDealerApiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/public/feed': {
      id: '/api/public/feed'
      path: '/api/public/feed'
      fullPath: '/api/public/feed'
      preLoaderRoute: typeof ApiPublicFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chaos.js': {
      id: '/api/public/chaos.js'
      path: '/api/public/chaos.js'
      fullPath: '/api/public/chaos.js'
      preLoaderRoute: typeof ApiPublicChaosDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dealer/$id': {
      id: '/admin/dealer/$id'
      path: '/dealer/$id'
      fullPath: '/admin/dealer/$id'
      preLoaderRoute: typeof AdminDealerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/cron/shopify-sync': {
      id: '/api/public/cron/shopify-sync'
      path: '/api/public/cron/shopify-sync'
      fullPath: '/api/public/cron/shopify-sync'
      preLoaderRoute: typeof ApiPublicCronShopifySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/saved-search-digest': {
      id: '/api/public/cron/saved-search-digest'
      path: '/api/public/cron/saved-search-digest'
      fullPath: '/api/public/cron/saved-search-digest'
      preLoaderRoute: typeof ApiPublicCronSavedSearchDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/digest': {
      id: '/api/public/cron/digest'
      path: '/api/public/cron/digest'
      fullPath: '/api/public/cron/digest'
      preLoaderRoute: typeof ApiPublicCronDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/quick-approve': {
      id: '/api/public/admin/quick-approve'
      path: '/api/public/admin/quick-approve'
      fullPath: '/api/public/admin/quick-approve'
      preLoaderRoute: typeof ApiPublicAdminQuickApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dealer/v1/stones': {
      id: '/api/dealer/v1/stones'
      path: '/api/dealer/v1/stones'
      fullPath: '/api/dealer/v1/stones'
      preLoaderRoute: typeof ApiDealerV1StonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/shopify/events': {
      id: '/api/public/hooks/shopify/events'
      path: '/api/public/hooks/shopify/events'
      fullPath: '/api/public/hooks/shopify/events'
      preLoaderRoute: typeof ApiPublicHooksShopifyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email/notify': {
      id: '/api/public/hooks/email/notify'
      path: '/api/public/hooks/email/notify'
      fullPath: '/api/public/hooks/email/notify'
      preLoaderRoute: typeof ApiPublicHooksEmailNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dealer/v1/stones/bulk': {
      id: '/api/dealer/v1/stones/bulk'
      path: '/bulk'
      fullPath: '/api/dealer/v1/stones/bulk'
      preLoaderRoute: typeof ApiDealerV1StonesBulkRouteImport
      parentRoute: typeof ApiDealerV1StonesRoute
    }
    '/api/dealer/v1/stones/$id': {
      id: '/api/dealer/v1/stones/$id'
      path: '/$id'
      fullPath: '/api/dealer/v1/stones/$id'
      preLoaderRoute: typeof ApiDealerV1StonesIdRouteImport
      parentRoute: typeof ApiDealerV1StonesRoute
    }
    '/admin/dealer/$id/stones/new': {
      id: '/admin/dealer/$id/stones/new'
      path: '/stones/new'
      fullPath: '/admin/dealer/$id/stones/new'
      preLoaderRoute: typeof AdminDealerIdStonesNewRouteImport
      parentRoute: typeof AdminDealerIdRoute
    }
    '/api/dealer/v1/stones/$id/mark-sold': {
      id: '/api/dealer/v1/stones/$id/mark-sold'
      path: '/mark-sold'
      fullPath: '/api/dealer/v1/stones/$id/mark-sold'
      preLoaderRoute: typeof ApiDealerV1StonesIdMarkSoldRouteImport
      parentRoute: typeof ApiDealerV1StonesIdRoute
    }
  }
}

interface AdminDealerIdRouteChildren {
  AdminDealerIdStonesNewRoute: typeof AdminDealerIdStonesNewRoute
}

const AdminDealerIdRouteChildren: AdminDealerIdRouteChildren = {
  AdminDealerIdStonesNewRoute: AdminDealerIdStonesNewRoute,
}

const AdminDealerIdRouteWithChildren = AdminDealerIdRoute._addFileChildren(
  AdminDealerIdRouteChildren,
)

interface AdminRouteChildren {
  AdminImportTestRoute: typeof AdminImportTestRoute
  AdminQuickApproveRoute: typeof AdminQuickApproveRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminDealerIdRoute: typeof AdminDealerIdRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminImportTestRoute: AdminImportTestRoute,
  AdminQuickApproveRoute: AdminQuickApproveRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminDealerIdRoute: AdminDealerIdRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardEnquiriesRoute: typeof DashboardEnquiriesRoute
  DashboardImportRoute: typeof DashboardImportRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  DashboardSalesRoute: typeof DashboardSalesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardDealerApiRoute: typeof DashboardDealerApiRoute
  DashboardDealerPricingRoute: typeof DashboardDealerPricingRoute
  DashboardDealerWhatsappRoute: typeof DashboardDealerWhatsappRoute
  DashboardJewellerApiRoute: typeof DashboardJewellerApiRoute
  DashboardJewellerEnquiriesRoute: typeof DashboardJewellerEnquiriesRoute
  DashboardJewellerFeedsRoute: typeof DashboardJewellerFeedsRoute
  DashboardJewellerMarkupRoute: typeof DashboardJewellerMarkupRoute
  DashboardJewellerOrdersRoute: typeof DashboardJewellerOrdersRoute
  DashboardJewellerSavedSearchesRoute: typeof DashboardJewellerSavedSearchesRoute
  DashboardJewellerShopifyRoute: typeof DashboardJewellerShopifyRoute
  DashboardJewellerWishlistRoute: typeof DashboardJewellerWishlistRoute
  DashboardStonesIdRoute: typeof DashboardStonesIdRoute
  DashboardStonesNewRoute: typeof DashboardStonesNewRoute
  DashboardJewellerIndexRoute: typeof DashboardJewellerIndexRoute
  DashboardStonesIndexRoute: typeof DashboardStonesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardEnquiriesRoute: DashboardEnquiriesRoute,
  DashboardImportRoute: DashboardImportRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  DashboardSalesRoute: DashboardSalesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardDealerApiRoute: DashboardDealerApiRoute,
  DashboardDealerPricingRoute: DashboardDealerPricingRoute,
  DashboardDealerWhatsappRoute: DashboardDealerWhatsappRoute,
  DashboardJewellerApiRoute: DashboardJewellerApiRoute,
  DashboardJewellerEnquiriesRoute: DashboardJewellerEnquiriesRoute,
  DashboardJewellerFeedsRoute: DashboardJewellerFeedsRoute,
  DashboardJewellerMarkupRoute: DashboardJewellerMarkupRoute,
  DashboardJewellerOrdersRoute: DashboardJewellerOrdersRoute,
  DashboardJewellerSavedSearchesRoute: DashboardJewellerSavedSearchesRoute,
  DashboardJewellerShopifyRoute: DashboardJewellerShopifyRoute,
  DashboardJewellerWishlistRoute: DashboardJewellerWishlistRoute,
  DashboardStonesIdRoute: DashboardStonesIdRoute,
  DashboardStonesNewRoute: DashboardStonesNewRoute,
  DashboardJewellerIndexRoute: DashboardJewellerIndexRoute,
  DashboardStonesIndexRoute: DashboardStonesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MarketplaceRouteChildren {
  MarketplaceSlugRoute: typeof MarketplaceSlugRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceSlugRoute: MarketplaceSlugRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

interface ApiDealerV1StonesIdRouteChildren {
  ApiDealerV1StonesIdMarkSoldRoute: typeof ApiDealerV1StonesIdMarkSoldRoute
}

const ApiDealerV1StonesIdRouteChildren: ApiDealerV1StonesIdRouteChildren = {
  ApiDealerV1StonesIdMarkSoldRoute: ApiDealerV1StonesIdMarkSoldRoute,
}

const ApiDealerV1StonesIdRouteWithChildren =
  ApiDealerV1StonesIdRoute._addFileChildren(ApiDealerV1StonesIdRouteChildren)

interface ApiDealerV1StonesRouteChildren {
  ApiDealerV1StonesIdRoute: typeof ApiDealerV1StonesIdRouteWithChildren
  ApiDealerV1StonesBulkRoute: typeof ApiDealerV1StonesBulkRoute
}

const ApiDealerV1StonesRouteChildren: ApiDealerV1StonesRouteChildren = {
  ApiDealerV1StonesIdRoute: ApiDealerV1StonesIdRouteWithChildren,
  ApiDealerV1StonesBulkRoute: ApiDealerV1StonesBulkRoute,
}

const ApiDealerV1StonesRouteWithChildren =
  ApiDealerV1StonesRoute._addFileChildren(ApiDealerV1StonesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  PendingApprovalRoute: PendingApprovalRoute,
  RequestsRoute: RequestsRoute,
  RetailRoute: RetailRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DocsApiRoute: DocsApiRoute,
  DocsDealerApiRoute: DocsDealerApiRoute,
  EmbedKeyRoute: EmbedKeyRoute,
  HowItWorksPaymentsRoute: HowItWorksPaymentsRoute,
  HowItWorksShippingRoute: HowItWorksShippingRoute,
  JewellersSlugRoute: JewellersSlugRoute,
  LearnSlugRoute: LearnSlugRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsDealersRoute: LegalTermsDealersRoute,
  LegalTermsJewellersRoute: LegalTermsJewellersRoute,
  SignUpDealerRoute: SignUpDealerRoute,
  SignUpJewellerRoute: SignUpJewellerRoute,
  StoneIdRoute: StoneIdRoute,
  VendorsSlugRoute: VendorsSlugRoute,
  JewellersIndexRoute: JewellersIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
  VendorsIndexRoute: VendorsIndexRoute,
  ApiPublicChaosDotjsRoute: ApiPublicChaosDotjsRoute,
  ApiPublicFeedRoute: ApiPublicFeedRoute,
  LearnGemstonesTypeRoute: LearnGemstonesTypeRoute,
  ApiDealerV1StonesRoute: ApiDealerV1StonesRouteWithChildren,
  ApiPublicAdminQuickApproveRoute: ApiPublicAdminQuickApproveRoute,
  ApiPublicCronDigestRoute: ApiPublicCronDigestRoute,
  ApiPublicCronSavedSearchDigestRoute: ApiPublicCronSavedSearchDigestRoute,
  ApiPublicCronShopifySyncRoute: ApiPublicCronShopifySyncRoute,
  ApiPublicHooksEmailNotifyRoute: ApiPublicHooksEmailNotifyRoute,
  ApiPublicHooksShopifyEventsRoute: ApiPublicHooksShopifyEventsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
